version: '2'
services:
  movies:
    build: ./movies

  bookings:
    build: ./bookings

  showtimes:
    build: ./showtimes

  users:
    build: ./users
    ports:
        - "5000-5001:5000"
    links:
      - bookings
      - movies

