version: '2'
services:
  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - movies
      - bookings
      - showtimes
      - users
    ports:
      - "8080:80"

  kong-migration:
    build: ./kong
    links:
      - kong-postgres
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-postgres
    command: kong migrations up

  kong:
    build: ./kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-postgres
      - KONG_LOG_LEVEL=debug
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    links:
      - movies
      - bookings
      - showtimes
      - users
      - kong-postgres
    depends_on:
      - kong-migration
    ports:
      - "9000:8000"
      - "9001:8001"

  kong-postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
    ports:
      - "5433:5432"

  movies:
    build: ./movies

  bookings:
    build: ./bookings

  showtimes:
    build: ./showtimes

  users:
    build: ./users
    links:
      - bookings
      - movies